# This Docker Compose file is used for development ONLY

services:
  nats:
    image: nats:2
    restart: always
    command: [ "-js" ]
    ports:
      - "127.0.0.1:4222:4222"
    networks:
      default:
        # Assign a static IP address for the Kubernetes "cluster" to access it
        ipv4_address: 172.30.100.10
  nats-init:
    image: natsio/nats-box
    restart: on-failure
    depends_on:
      - nats
    entrypoint: [ "/docker-entrypoint.sh" ]
    environment:
      NATS_URL: "nats://nats:4222"
    volumes:
      - "./data/test/nats-seed.sh:/docker-entrypoint.sh:roZ"
  k3s:
    # https://hub.docker.com/r/rancher/k3s/tags
    image: rancher/k3s:v1.30.2-k3s1
    restart: always
    command: [ "server", "--disable=traefik,servicelb,local-storage" ]
    privileged: true
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    environment:
      K3S_KUBECONFIG_OUTPUT: "/output/kubeconfig"
      K3S_KUBECONFIG_MODE: "666"
    volumes:
      - "./run/k3s/:/output/:Z"
      - "./data/test/k8s_resources.yaml:/var/lib/rancher/k3s/server/manifests/kriger.yaml:roZ"
      - "./data/test/k8s_registries.yaml:/etc/rancher/k3s/registries.yaml:roZ"
    ports:
      - "127.0.0.1:6443:6443"
  registry:
    image: registry:2
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - registry:/var/lib/registry
  jeager:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 127.0.0.1:4317:4317
      - 127.0.0.1:16686:16686

volumes:
  registry:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.100.0/24
          gateway: 172.30.100.1
