[package]
name = "kriger_submitter"
version = "0.0.1"
edition = "2021"

[features]

[dependencies]
color-eyre.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
