[package]
name = "kriger_runner"
version = "0.0.1"
edition = "2021"

[features]

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
kriger_common = { path = "../kriger_common" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
