[package]
name = "kriger_runner"
version = "0.0.1"
edition = "2021"

[features]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
clap_derive = { workspace = true }
futures = { workspace = true }
kriger_common = { path = "../kriger_common" }
num_cpus = "1.16.0"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
