import { FLAG_CODE, SERVICE_STATUS } from "./enums";
import type { FlagSubmissionResult } from "./types";

export const CONFIG = {};

// Dummy data constants
export const DUMMY_SCOREBOARD_DATA = {
  teams: {
    "10.0.1.1": {
      ip_address: "10.0.1.1",
      name: "NOP",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.2.1": {
      ip_address: "10.0.2.1",
      name: "Cyberlandslaget",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.3.1": {
      ip_address: "10.0.3.1",
      name: "Iku-toppene",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.4.1": {
      ip_address: "10.0.4.1",
      name: "Bootplug",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.5.1": {
      ip_address: "10.0.5.1",
      name: "Corax",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.6.1": {
      ip_address: "10.0.6.1",
      name: "RumbleInTheJungle",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.7.1": {
      ip_address: "10.0.7.1",
      name: "coldboots",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.8.1": {
      ip_address: "10.0.8.1",
      name: "Norske Nøkkelsnikere",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.9.1": {
      ip_address: "10.0.9.1",
      name: "EPT",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
    "10.0.10.1": {
      ip_address: "10.0.10.1",
      name: "mode13h",
      services: {
        "CheesyCheats-1": SERVICE_STATUS.OK,
        "CheesyCheats-2": SERVICE_STATUS.OK,
        Polls: SERVICE_STATUS.OK,
        "GadgetHorse-1": SERVICE_STATUS.OK,
        "GadgetHorse-2": SERVICE_STATUS.OK,
        MineCClicker: SERVICE_STATUS.OK,
      },
    },
  },
};

export const DUMMY_FLAGSUBMISSION_LOG: FlagSubmissionResult[] = [
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.1.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Ok,
    points: 13.37,
    tick: 1,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.1.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Ok,
    points: 13.37,
    tick: 2,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.1.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Old,
    points: 13.37,
    tick: 4,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.1.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Error,
    points: 13.37,
    tick: 3,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.3.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Old,
    points: 13.37,
    tick: 2,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.3.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Old,
    points: 13.37,
    tick: 2,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.3.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Ok,
    points: 0,
    tick: 2,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.3.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Duplicate,
    points: 0,
    tick: 2,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.1.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Ok,
    points: 0,
    tick: 1,
  },
  {
    flag: "ECSC_KcpNAJ2gTzNviLzZE6hsIKIEJqbV4Dcr",
    team_id: "10.0.2.1",
    service: "Polls",
    exploit: "polls-v1",
    status: FLAG_CODE.Duplicate,
    points: 0,
    tick: 1,
  },
];

// TODO: fix correct struct
export const DUMMY_EXECUTION_LOG = [
  {
    id: 1,
    exploit_id: 1,
    output: "2.056 ./scripts/s1.py timed out!",
    exit_code: 1,
    started_at: new Date(13).toUTCString(),
    finished_at: new Date(13).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 2,
    exploit_id: 1,
    output: "0.054 Finished ./scripts/s2.py",
    exit_code: 0,
    started_at: new Date(12).toUTCString(),
    finished_at: new Date(12).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 3,
    exploit_id: 1,
    output: `0.054 ./scripts/s2.py: Traceback (most recent call last):\nFile "/home/kat/Documents/benchmarking/./scripts/s2.py", line 1, in <module>\n		f = open("lpol", "r")\nFileNotFoundError: [Errno 2] No such file or directory: 'lpol'`,
    exit_code: 0,
    started_at: new Date(11).toUTCString(),
    finished_at: new Date(11).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 4,
    exploit_id: 1,
    output: "0.016 Finished ./scripts/inner/is2.py",
    exit_code: 0,
    started_at: new Date(10).toUTCString(),
    finished_at: new Date(10).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 5,
    exploit_id: 1,
    output: "0.016 ./scripts/inner/is2.py: is2",
    exit_code: 0,
    started_at: new Date(9).toUTCString(),
    finished_at: new Date(9).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 6,
    exploit_id: 1,
    output: "0.012 Finished ./scripts/s3.py",
    exit_code: 0,
    started_at: new Date(8).toUTCString(),
    finished_at: new Date(8).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 7,
    exploit_id: 1,
    output: "0.012 Finished ./scripts/inner/is1.py",
    exit_code: 0,
    started_at: new Date(7).toUTCString(),
    finished_at: new Date(7).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 8,
    exploit_id: 1,
    output: "0.012 ./scripts/inner/is1.py: is1",
    exit_code: 0,
    started_at: new Date(6).toUTCString(),
    finished_at: new Date(6).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 9,
    exploit_id: 1,
    output: "0.012 ./scripts/s3.py: s3",
    exit_code: 0,
    started_at: new Date(5).toUTCString(),
    finished_at: new Date(5).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 10,
    exploit_id: 1,
    output: "0.000 Running ./scripts/s3.py",
    exit_code: 0,
    started_at: new Date(4).toUTCString(),
    finished_at: new Date(4).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 11,
    exploit_id: 1,
    output: "0.000 Running ./scripts/inner/is1.py",
    exit_code: 0,
    started_at: new Date(3).toUTCString(),
    finished_at: new Date(3).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 12,
    exploit_id: 1,
    output: "0.000 Running ./scripts/s2.py",
    exit_code: 0,
    started_at: new Date(2).toUTCString(),
    finished_at: new Date(2).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 13,
    exploit_id: 1,
    output: "0.000 Running ./scripts/s1.py",
    exit_code: 0,
    started_at: new Date(1).toUTCString(),
    finished_at: new Date(1).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
  {
    id: 14,
    exploit_id: 1,
    output: "0.000 Running ./scripts/inner/is2.py",
    exit_code: 0,
    started_at: new Date(0).toUTCString(),
    finished_at: new Date(0).toUTCString(),
    target_id: 1,

    service: "testservice",
    target_tick: 1,
    team: "10.0.1.1",
  },
];
