permissions: read-all
on:
  push:
    branches: [ main ]

name: Build container images

jobs:
  build:
    name: Build ${{ matrix.tag }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: kriger/kriger
            path: .
            cache:
              key: rust
              files: "Cargo.lock"
          - tag: kriger/frontend
            path: frontend
            cache:
              key: pnpm
              files: "frontend/pnpm-lock.yaml"
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: builder
        with:
          # See: https://github.com/docker/buildx/issues/298
          driver-opts: |
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: r.o99.no
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Set up build cache
        uses: actions/cache@v4
        with:
          path: ${{ matrix.cache.key }}-build-cache
          key: ${{ runner.os }}-${{ matrix.cache.key }}-build-cache-${{ hashFiles(matrix.cache.files) }}

      - name: Inject build cache
        uses: reproducible-containers/buildkit-cache-dance@5b6db76d1da5c8b307d5d2e0706d266521b710de # v3.1.2
        with:
          cache-source: ${{ matrix.cache.key }}-build-cache

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/Dockerfile
          push: true
          tags: r.o99.no/${{ matrix.tag }}:latest,r.o99.no/${{ matrix.tag }}:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          builder: ${{ steps.builder.outputs.name }}

  build_exploit_base:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: kriger/exploit-base:python
            path: data/base/python
    name: Build exploit base ${{ matrix.tag }}
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: builder
        with:
          driver-opts: |
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: r.o99.no
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/Dockerfile
          push: true
          tags: r.o99.no/${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          builder: ${{ steps.builder.outputs.name }}
