permissions: read-all
on:
  push:
    branches: [ main ]

name: Build container images

jobs:
  build:
    name: Build kriger
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # See: https://github.com/docker/buildx/issues/298
          driver-opts: |
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: r.o99.no
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: r.o99.no/kriger/kriger:latest,r.o99.no/kriger/kriger:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
#          platforms: linux/amd64,linux/arm64
  build_exploit_base:
    strategy:
      matrix:
        include:
          - tag: kriger/exploit-base:python
            path: data/base/python
    name: Build exploit base ${{ matrix.tag }}
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: r.o99.no
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/Dockerfile
          push: true
          tags: r.o99.no/${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
#          platforms: linux/amd64,linux/arm64
