name: Release kriger

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: read-all

jobs:
  release-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build -p kriger --release && strip target/release/kriger && mv target/release/kriger target/release/kriger_amd64

      - name: Release
        uses: softprops/action-gh-release@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/kriger_amd64

