on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/templates.yml"
      - "data/templates/**"
  workflow_dispatch:

name: Package templates

jobs:
  package-templates:
    name: Package exploit template ${{ matrix.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: python
          - name: python-slim
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up ORAS
        uses: oras-project/setup-oras@ca28077386065e263c03428f4ae0c09024817c93 # v1.2.0

      - name: Log in to the OCI registry
        run: |
          oras login -u "$REGISTRY_USER" --password-stdin ghcr.io <<<"$REGISTRY_PASS"
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASS: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive the template
        run: |
          tar czfh template.tar.gz -C "data/templates/${{ matrix.name }}" .

      - name: Push the template
        run: |
          oras push ghcr.io/cyberlandslaget/kriger-exploit-templates:${{ matrix.name }} template.tar.gz:application/vnd.kriger.exploit.template.v1.tar+gzip
